### PR TITLE
Task/add npmrc

### PR DESCRIPTION
**Pull request by paulmskim**
**Ticket:** N/A

This PR sets up an `.npmrc` file so that we can set up github packages for this repo.

**Artifact:**

image

image

### CODE REVIEW

**Comment by paulmskim** [comment]
@borkweb we still have a `master` branch in this repo, I created a `main` branch off of the `master` branch, can we delete the `master` branch and set the `main` branch as the default?

**Review by borkweb — APPROVED** [review]
:+1:

**Comment by borkweb** [comment]
Yeah, I'll ditch the antiquated `master` branch

**Comment by paulmskim** [comment]
Holding the merge on this, once we release on npm we won't need this PR

**Comment by paulmskim** [comment]
Closing in favor of https://github.com/the-events-calendar/product-taskmaster/pull/36. We are also publishing on npm, not GH packages.

**Pull request closed without merging**
